export function getMainCloud(): string {
  return [
    '// Cloud Component Entry Point',
    '//',
    '// Your component runs on the server as a Node.js process.',
    '// The execution engine provides these globals:',
    '//',
    '//   thatOpenServices  - EngineServicesClient instance (authenticated)',
    '//   executionParams   - Parameters passed by the caller',
    '//   executionReporter - { message(msg), progress(pct) } for live feedback',
    '//   OBC              - @thatopen/components',
    '//   THREE            - three',
    '//   WEBIFC           - web-ifc',
    '//   fs               - Node.js fs module',
    '//',
    '// Your main() function must return { type, message }:',
    '//   type: "SUCCESS" | "FAIL" | "WARNING"',
    '',
    '// Globals injected by the execution engine at runtime',
    'declare const thatOpenServices: import("thatopen-services").EngineServicesClient;',
    'declare const executionParams: Record<string, any>;',
    'declare const executionReporter: {',
    '  message(msg: string): void;',
    '  progress(pct: number): void;',
    '};',
    'declare const OBC: typeof import("@thatopen/components");',
    'declare const THREE: typeof import("three");',
    'declare const fs: typeof import("fs");',
    '',
    'export async function main() {',
    '  const components = new OBC.Components();',
    '  executionReporter.message("Components initialized: " + !!components);',
    '',
    '  // Example: read caller parameters',
    '  // const { inputFile } = executionParams;',
    '',
    '  executionReporter.progress(100);',
    '  return { type: "SUCCESS", message: "Done" };',
    '}',
    '',
  ].join('\n');
}
